[project]
name = "timetable"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Amaan", email = "amaanarmaanmuhammad@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "ortools>=9.15.6755",
]

[project.scripts]
timetable = "timetable:main"

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"
